// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tatqpiumfadybaflziue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdHFwaXVtZmFkeWJhZmx6aXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDAyMjEsImV4cCI6MjA3MTc3NjIyMX0.CrWVt3-EKqGgS0drPWmbPsVbkMC8fGbvJeWLRBEE5Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});